# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "plone-org DevOps"
    vb.memory = 2048
    vb.cpus = 1
  end
  config.vm.provider "libvirt" do |lv|
    lv.title = "plone-org DevOps"
    lv.memory = 2048
    lv.cpus = 1
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook-setup.yml"
  end
end
