version: '3.3'

services:
  traefik:
    image: traefik:v2.9

    ports:
      - 80:80
      - 443:443

    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.middlewares.admin-auth.basicauth.users=admin:$$apr1$Jv7k2JvK$uNmYFBXyov5NYPm/SzB09/
        - traefik.http.routers.traefik-public-https.rule=Host(`traefik-beta.plone.org`)
        - traefik.http.routers.traefik-public-https.entrypoints=https
        - traefik.http.routers.traefik-public-https.tls=true
        - traefik.http.routers.traefik-public-https.service=api@internal
        # - traefik.http.routers.traefik-public-https.middlewares=admin-auth
        - traefik.http.services.traefik-public.loadbalancer.server.port=8000

        # GENERIC MIDDLEWARES
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.middlewares.gzip.compress=true
        - traefik.http.middlewares.gzip.compress.excludedcontenttypes=image/png, image/jpeg, font/woff2

        # GENERIC ROUTERS
        - traefik.http.routers.generic-https-redirect.entrypoints=http
        - traefik.http.routers.generic-https-redirect.rule=HostRegexp(`{host:.*}`)
        - traefik.http.routers.generic-https-redirect.priority=1
        - traefik.http.routers.generic-https-redirect.middlewares=https-redirect

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-public-certificates:/certificates
      - traefik-config:/config

    command:
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmmode
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.email=admin@plone.org
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --providers.file.filename=/config/traefik_config.yaml
      - --accesslog
      - --log
      - --api

    networks:
      - traefik-public

  varnish:
    image: varnish:stable
    configs:
      - source: varnishvcl
        target: /etc/varnish/default.vcl
    tmpfs:
      - /var/lib/varnish:exec
    networks:
      - traefik-public
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # SERVICE
        - traefik.http.services.varnish.loadbalancer.server.port=80

  frontend:
    image: ghcr.io/plone/ploneorg-frontend:latest
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
    depends_on:
      - backend
    networks:
    - traefik-public
    - backend
    deploy:
      replicas: 2
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # SERVICE
        - traefik.http.services.plone-frontend.loadbalancer.server.port=3000
        # HOSTS
        # -> Varnish Public
        - traefik.http.routers.backend-varnish-intern.rule=Host(`beta.plone.org`)
        - traefik.http.routers.backend-varnish-intern.entrypoints=https
        - traefik.http.routers.backend-varnish.tls=true
        - traefik.http.routers.backend-varnish-intern.service=varnish
        # Plone Intern
        - traefik.http.routers.frontend.rule=Host(`beta.plone.org`) && Headers(`X-Varnish-Routed`,`1`)
        - traefik.http.routers.frontend.entrypoints=https
        - traefik.http.routers.frontend.tls=true
        - traefik.http.routers.frontend.tls.certresolver=le
        - traefik.http.routers.frontend.service=plone-frontend
        - traefik.http.routers.frontend.middlewares=gzip

  backend:
    image: ghcr.io/plone/ploneorg-backend:latest
    environment:
      RELSTORAGE_DSN: "dbname='plone' user='plone' host='db' password='plone'"
    depends_on:
      - db
    networks:
      - traefik-public
      - backend
    deploy:
      replicas: 2
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # AUTHENTICATION
        # Note: all dollar signs in the hash need to be doubled for escaping.
        # To create user:password pair, it's possible to use this command:
        # echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
        # Defaults to admin:admin
        - traefik.http.middlewares.backend-auth.basicauth.users=ploneorg:$$apr1$$SAOhBRqM$$HqoYLlr//h7PfUWidoFg//
        # SERVICE
        - traefik.http.services.plone-backend.loadbalancer.server.port=8080
        # Plone API
        # -> Varnish Public
        - traefik.http.routers.backend-varnish-intern.rule=Host(`beta.plone.org`) && (PathPrefix(`/++api++`))
        - traefik.http.routers.backend-varnish-intern.entrypoints=https
        - traefik.http.routers.backend-varnish.tls=true
        - traefik.http.routers.backend-varnish-intern.service=varnish
        # -> Plone Intern
        - traefik.http.routers.backend.rule=Host(`beta.plone.org`) && (PathPrefix(`/++api++`)) && Headers(`X-Varnish-Routed`,`1`)
        - traefik.http.routers.backend.entrypoints=https
        - traefik.http.routers.backend.tls=true
        - traefik.http.routers.backend.service=plone-backend
        - "traefik.http.middlewares.backend.replacepathregex.regex=^/\\+\\+api\\+\\+($$|/.*)"
        - "traefik.http.middlewares.backend.replacepathregex.replacement=/VirtualHostBase/https/beta.plone.org/Plone/++api++/VirtualHostRoot/$$1"
        - traefik.http.routers.backend.middlewares=gzip,backend
        # Plone ClassicUI - uncomment if not needed - protected with basic auth (prevent SEOs from crawl it)
        - traefik.http.routers.backend-classic.rule=Host(`beta.plone.org`) && PathPrefix(`/ClassicUI`)
        - traefik.http.routers.backend-classic.entrypoints=https
        - traefik.http.routers.backend-classic.tls=true
        - traefik.http.routers.backend-classic.service=plone-backend
        - "traefik.http.middlewares.backend-classic.replacepathregex.regex=^/ClassicUI($$|/.*)"
        - "traefik.http.middlewares.backend-classic.replacepathregex.replacement=/VirtualHostBase/https/beta.plone.org/Plone/VirtualHostRoot/_vh_ClassicUI/$$1"
        - traefik.http.routers.backend-classic.middlewares=gzip,backend-classic
        # Plone ZMI - uncomment if not needed - protected with basic auth (prevent SEOs from crawl it)
        - traefik.http.routers.backend-zmi.rule=Host(`beta.plone.org`) && PathPrefix(`/zmi`)
        - traefik.http.routers.backend-zmi.entrypoints=https
        - traefik.http.routers.backend-zmi.tls=true
        - traefik.http.routers.backend-zmi.service=plone-backend
        - "traefik.http.middlewares.backend-zmi.replacepathregex.regex=^/zmi($$|/.*)"
        - "traefik.http.middlewares.backend-zmi.replacepathregex.replacement=/VirtualHostBase/https/beta.plone.org/VirtualHostRoot/_vh_zmi/$$1"
        - traefik.http.routers.backend-zmi.middlewares=gzip,backend-zmi

  db:
    image: postgres:14.2
    environment:
      POSTGRES_USER: plone
      POSTGRES_PASSWORD: plone
      POSTGRES_DB: plone
    volumes:
    - site-data:/var/lib/postgresql/data
    networks:
    - backend

configs:
  varnishvcl:
    # name: ploneorg-varnish-0001
    file: ./default.vcl

volumes:
  traefik-public-certificates:
    driver_opts:
      type: none
      device: /data/traefik/certificates
      o: bind
  traefik-config:
    driver_opts:
      type: none
      device: /data/traefik/config
      o: bind
  site-data:
    driver_opts:
      type: none
      device: /srv/plone.org/data
      o: bind

networks:
  traefik-public:
    external: true
    driver: overlay
  backend:
    driver: overlay

