name: Deploy latest image tags to testing.plone.org 

on:
  workflow_dispatch:

jobs:

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    concurrency: deploy_testing
    runs-on: ubuntu-latest
    environment: 
      name: testing.plone.org
      url: https://testing.plone.org
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy 'latest' image tags to testing.plone.org
        uses: kitconcept/docker-stack-deploy@v1.2.0
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.DEPLOY_GHCR_READ_TOKEN }}
          remote_host: ${{ vars.DEPLOY_HOST }}
          remote_port: ${{ vars.DEPLOY_PORT }}
          remote_user: ${{ vars.DEPLOY_USER }}
          remote_private_key: ${{ secrets.DEPLOY_SSH }}
          stack_file: "devops/stacks/testing.plone.org.yml"
          stack_name: "testing-plone-org"
          env_file: |
            STACK_NAME=testing-plone-org
            DB_HOST=${{ vars.DB_HOST }}
            DB_NAME=${{ vars.DB_NAME }}
            DB_USER=${{ vars.DB_USER }}
            DB_PORT=${{ vars.DB_PORT }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          deploy_timeout: 480
